### ISSUE TITLE
Document csv export and re-import

### ISSUE THREAD

**Issue by bill-anderson** [devinit/data-governance-db#11]
Export documents - including all ids and descriptions - to csv. And allow for re-import. This isn't urgent but will allow for restructuring of classifications as the analysis matures

**Comment by akmiller01** [comment]
https://github.com/devinit/data-governance-db/commit/06cf9bc30ec26fd955b7423fbd75e9d2eb5d80b7

**Comment by akmiller01** [comment]
Done and deployed. I went ahead with an off-the-shelf solution for this, so you'll find it built into the Admin panel here: https://datagov.devinit.org/admin/core/document/

![image](https://github.com/devinit/data-governance-db/assets/2836840/2be3cb1f-b3b1-4f4f-ba82-508afc6e32ba)

It should automatically detect which rows have changed, and warn you what it's about to do upon re-import.

**Comment by bill-anderson** [comment]
Does the documents table store the lookup ids or descriptions?

**Comment by akmiller01** [comment]
By default it would export and expect from an import the ID of a foreign-key field. But I've configured it to expect the name of the foreign-key related object instead of the ID:

https://github.com/devinit/data-governance-db/blob/main/core/admin.py#L54-L68

**Comment by bill-anderson** [comment]
Can it do both?
If not can we export the ids and all the tables?

**Comment by akmiller01** [comment]
Done, it does both ID and name for related fields now. But the name fields are read-only for import purposes. So if an ID changes, it will update the value to match the ID, and ignore the name column.

**Comment by bill-anderson** [comment]
Perfect, thanks
