### ISSUE TITLE
CSV export for read-only users

### ISSUE THREAD

**Issue by bill-anderson** [devinit/data-governance-db#13]
Could we also have a csv export without Ids accessed from the documents list that ordinary users can download? (Admin version for bulk editing)

**Comment by akmiller01** [comment]
https://github.com/devinit/data-governance-db/commit/475eb3f4d87d8cb02303375e8189fb7772d78a60

**Comment by akmiller01** [comment]
Deployed. Button on the document list responds to filters, but default all export is here https://datagov.devinit.org/documents/export
