### ISSUE TITLE
Password manager misbehaving when editing a user

### ISSUE THREAD

**Issue by bill-anderson** [devinit/data-governance-db#14]
I use a password manager (with autofill) to log in to the DB
When I go to edit a user the autofill insists on changing the username (see pic). Is this something you can disable, or do i need to disable my pwd manager?

![uedit](https://github.com/devinit/data-governance-db/assets/3491562/07c76ef1-6b7b-4db7-b19a-56098247049c)

**Comment by akmiller01** [comment]
Evidently there's not much we can do about this. I've tried setting `autocomplete: false`, but the browser ignores it and changes it. There's a war between web-designers and password-managers, and the password-managers have decided to override the HTML metadata and autofill anything they can: https://stackoverflow.com/questions/22661977/disabling-safari-autofill-on-usernames-and-passwords
