### ISSUE TITLE
Documents list filters

### ISSUE THREAD

**Issue by bill-anderson** [devinit/data-governance-db#3]
Clicking on Institution, category and type hyperlinked values should filter the list by that value.

(This ^^ rather than going to a separate list?)

**Comment by akmiller01** [comment]
https://github.com/devinit/data-governance-db/commit/cd1fb780fe5101617482312b68410c909cabc594

**Comment by akmiller01** [comment]
Deployed @bill-anderson.

I went ahead and made the filters additive. So if you're filtering by document type, and click on a category, it will then be filtering by both document type and category. Let me know if you'd rather have it only have one filter active at a time. Also went ahead and added pagination, with a total of 20 documents before new pages start appearing.

**Comment by bill-anderson** [comment]
I think double filtering will work. Let me check once I have more documents in there
