### ISSUE TITLE
Add and edit document details

### ISSUE THREAD

**Issue by bill-anderson** [devinit/data-governance-db#4]
Only for full access users

**Comment by akmiller01** [comment]
https://github.com/devinit/data-governance-db/commit/46de8a8ba37f3dff90bd2e77ed94c1ff1e8ba3c8

**Comment by akmiller01** [comment]
Deployed @bill-anderson.

Permissions are done like the capacity planner, so you can create/assign user groups with granular add/edit/delete permissions for each model.
