### ISSUE TITLE
User smaller font on documents list

### ISSUE THREAD

**Issue by bill-anderson** [devinit/data-governance-db#6]
Same as CapPlan projects list

https://datagov.devinit.org/documents
https://capacity.devinit.org/projects

**Comment by akmiller01** [comment]
Hey Bill,

These are already the same font/font-size, do you still want the document list font-size smaller?

![image](https://github.com/devinit/data-governance-db/assets/2836840/9f3d94ea-0340-4ef7-89d6-d30eff223fb6)

**Comment by bill-anderson** [comment]
Mine is different
??
![font](https://github.com/devinit/data-governance-db/assets/3491562/88767214-daa9-4add-8e35-3ae3c7c65627)

**Comment by bill-anderson** [comment]
Oops
Ignore me
Was my browser setting
I had CapPLan at 75%
But smaller would be better

**Comment by akmiller01** [comment]
https://github.com/devinit/data-governance-db/commit/d4a5f46206a5c11d38a6c91072fe529f7d9a6562

**Comment by akmiller01** [comment]
Deployed, about 3 pt smaller for both table cells and table headers.
