### ISSUE TITLE
Handling of institutions, types, etc

### ISSUE THREAD

**Issue by bill-anderson** [devinit/data-governance-db#7]
From main menu go to table of values with document counts. 

Hyperlink on name, not id.
"Add" button for editors

Will this work if you select a value...?
For editors go to edit detail record. For other users go to the documents list with the selected value being the applied filter

**Comment by akmiller01** [comment]
https://github.com/devinit/data-governance-db/commit/bb61098a8def36aed5a10d7c65ff727ae6923f57

**Comment by akmiller01** [comment]
Done and deployed. This was a large one, adding add/edit/delete permission-locked buttons and pages for all the remaining models. So please check this one with both types of accounts!

**Comment by bill-anderson** [comment]
All good
And I have checked creating read-only user with external email and converting it to full user (and back)
