### ISSUE TITLE
Make u.r.l. mandatory but don't check for valid u.r.l.

### ISSUE THREAD

**Issue by bill-anderson** [devinit/data-governance-db#9]
Need to log documents that can't be found. 

EITHER 
Allow n.a. as a valid entry
OR
Create u.r.l datagov.devinit.org/file-not-available with text "This document is known to exist but is currently not available."

**Comment by bill-anderson** [comment]
On second thoughts "n.a." would be clearer

**Comment by akmiller01** [comment]
https://github.com/devinit/data-governance-db/commit/41c41f1efaa23b16f52c3083ab97f301228096ea

**Comment by akmiller01** [comment]
Done and deployed. It allows any upper/lowercase combination of NA and periods, like "n.a" or "n.a." as well as valid URLs. And then only displays valid URLs on the display page, otherwise displaying "This document is known to exist but is currently not available."
